// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/priceutils.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceData struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LastPrice   *string                `protobuf:"bytes,1,opt,name=last_price,json=lastPrice"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PriceData) Reset() {
	*x = PriceData{}
	mi := &file_proto_priceutils_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceData) ProtoMessage() {}

func (x *PriceData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_priceutils_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PriceData) GetLastPrice() string {
	if x != nil {
		if x.xxx_hidden_LastPrice != nil {
			return *x.xxx_hidden_LastPrice
		}
		return ""
	}
	return ""
}

func (x *PriceData) SetLastPrice(v string) {
	x.xxx_hidden_LastPrice = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *PriceData) HasLastPrice() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PriceData) ClearLastPrice() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LastPrice = nil
}

type PriceData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LastPrice *string
}

func (b0 PriceData_builder) Build() *PriceData {
	m0 := &PriceData{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LastPrice != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_LastPrice = b.LastPrice
	}
	return m0
}

type TimeSeriesItemWithSymbol struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TimeInUnixMicros int64                  `protobuf:"varint,1,opt,name=time_in_unix_micros,json=timeInUnixMicros"`
	xxx_hidden_Symbol           *string                `protobuf:"bytes,2,opt,name=symbol"`
	xxx_hidden_Data             *PriceData             `protobuf:"bytes,3,opt,name=data"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *TimeSeriesItemWithSymbol) Reset() {
	*x = TimeSeriesItemWithSymbol{}
	mi := &file_proto_priceutils_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesItemWithSymbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesItemWithSymbol) ProtoMessage() {}

func (x *TimeSeriesItemWithSymbol) ProtoReflect() protoreflect.Message {
	mi := &file_proto_priceutils_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TimeSeriesItemWithSymbol) GetTimeInUnixMicros() int64 {
	if x != nil {
		return x.xxx_hidden_TimeInUnixMicros
	}
	return 0
}

func (x *TimeSeriesItemWithSymbol) GetSymbol() string {
	if x != nil {
		if x.xxx_hidden_Symbol != nil {
			return *x.xxx_hidden_Symbol
		}
		return ""
	}
	return ""
}

func (x *TimeSeriesItemWithSymbol) GetData() *PriceData {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *TimeSeriesItemWithSymbol) SetTimeInUnixMicros(v int64) {
	x.xxx_hidden_TimeInUnixMicros = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *TimeSeriesItemWithSymbol) SetSymbol(v string) {
	x.xxx_hidden_Symbol = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *TimeSeriesItemWithSymbol) SetData(v *PriceData) {
	x.xxx_hidden_Data = v
}

func (x *TimeSeriesItemWithSymbol) HasTimeInUnixMicros() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TimeSeriesItemWithSymbol) HasSymbol() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TimeSeriesItemWithSymbol) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *TimeSeriesItemWithSymbol) ClearTimeInUnixMicros() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TimeInUnixMicros = 0
}

func (x *TimeSeriesItemWithSymbol) ClearSymbol() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Symbol = nil
}

func (x *TimeSeriesItemWithSymbol) ClearData() {
	x.xxx_hidden_Data = nil
}

type TimeSeriesItemWithSymbol_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TimeInUnixMicros *int64
	Symbol           *string
	Data             *PriceData
}

func (b0 TimeSeriesItemWithSymbol_builder) Build() *TimeSeriesItemWithSymbol {
	m0 := &TimeSeriesItemWithSymbol{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TimeInUnixMicros != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_TimeInUnixMicros = *b.TimeInUnixMicros
	}
	if b.Symbol != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Symbol = b.Symbol
	}
	x.xxx_hidden_Data = b.Data
	return m0
}

type TimeSeriesWithSymbol struct {
	state            protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*TimeSeriesItemWithSymbol `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TimeSeriesWithSymbol) Reset() {
	*x = TimeSeriesWithSymbol{}
	mi := &file_proto_priceutils_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesWithSymbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesWithSymbol) ProtoMessage() {}

func (x *TimeSeriesWithSymbol) ProtoReflect() protoreflect.Message {
	mi := &file_proto_priceutils_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TimeSeriesWithSymbol) GetItems() []*TimeSeriesItemWithSymbol {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *TimeSeriesWithSymbol) SetItems(v []*TimeSeriesItemWithSymbol) {
	x.xxx_hidden_Items = &v
}

type TimeSeriesWithSymbol_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*TimeSeriesItemWithSymbol
}

func (b0 TimeSeriesWithSymbol_builder) Build() *TimeSeriesWithSymbol {
	m0 := &TimeSeriesWithSymbol{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

var File_proto_priceutils_proto protoreflect.FileDescriptor

const file_proto_priceutils_proto_rawDesc = "" +
	"\n" +
	"\x16proto/priceutils.proto\x12\x05proto\"*\n" +
	"\tPriceData\x12\x1d\n" +
	"\n" +
	"last_price\x18\x01 \x01(\tR\tlastPrice\"\x87\x01\n" +
	"\x18TimeSeriesItemWithSymbol\x12-\n" +
	"\x13time_in_unix_micros\x18\x01 \x01(\x03R\x10timeInUnixMicros\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.proto.PriceDataR\x04data\"M\n" +
	"\x14TimeSeriesWithSymbol\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.proto.TimeSeriesItemWithSymbolR\x05itemsB<Z:github.com/glennhartmann/ledger-tools/src/priceutils/protob\beditionsp\xe9\a"

var file_proto_priceutils_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_priceutils_proto_goTypes = []any{
	(*PriceData)(nil),                // 0: proto.PriceData
	(*TimeSeriesItemWithSymbol)(nil), // 1: proto.TimeSeriesItemWithSymbol
	(*TimeSeriesWithSymbol)(nil),     // 2: proto.TimeSeriesWithSymbol
}
var file_proto_priceutils_proto_depIdxs = []int32{
	0, // 0: proto.TimeSeriesItemWithSymbol.data:type_name -> proto.PriceData
	1, // 1: proto.TimeSeriesWithSymbol.items:type_name -> proto.TimeSeriesItemWithSymbol
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_priceutils_proto_init() }
func file_proto_priceutils_proto_init() {
	if File_proto_priceutils_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_priceutils_proto_rawDesc), len(file_proto_priceutils_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_priceutils_proto_goTypes,
		DependencyIndexes: file_proto_priceutils_proto_depIdxs,
		MessageInfos:      file_proto_priceutils_proto_msgTypes,
	}.Build()
	File_proto_priceutils_proto = out.File
	file_proto_priceutils_proto_goTypes = nil
	file_proto_priceutils_proto_depIdxs = nil
}
